/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/pocketsync/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PocketCastsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_POCKETCASTS = "pocketsync-history";
var API_BASE = "https://api.pocketcasts.com";
var MIN_LISTEN_SECONDS = 5 * 60;
var DEFAULT_SETTINGS = {
  email: "",
  password: "",
  token: "",
  notePath: "personal/podcasts",
  noteFilename: "{{podcast_name}} - {{podcast_episode}}.md",
  templaterFile: "_templater_templates/Podcast"
};
function isConsidered(ep) {
  return ep.playingStatus === 3 || ep.playedUpTo >= MIN_LISTEN_SECONDS;
}
function formatDuration(seconds) {
  if (!seconds)
    return "0m";
  const h = Math.floor(seconds / 3600);
  const m = Math.floor(seconds % 3600 / 60);
  if (h > 0)
    return `${h}h ${m}m`;
  return `${m}m`;
}
function formatDate(dateStr) {
  if (!dateStr)
    return "";
  const d = new Date(dateStr);
  return d.toLocaleDateString(void 0, { year: "numeric", month: "short", day: "numeric" });
}
function progressPct(ep) {
  if (!ep.duration)
    return ep.playingStatus === 3 ? 100 : 0;
  return Math.min(100, Math.round(ep.playedUpTo / ep.duration * 100));
}
async function apiLogin(email, password) {
  const resp = await (0, import_obsidian.requestUrl)({
    url: `${API_BASE}/user/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email, password, scope: "webplayer" })
  });
  if (resp.status !== 200)
    throw new Error(`Login failed (${resp.status})`);
  return resp.json.token;
}
async function apiFetchHistory(token) {
  var _a;
  const resp = await (0, import_obsidian.requestUrl)({
    url: `${API_BASE}/user/history`,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`
    },
    body: JSON.stringify({})
  });
  if (resp.status !== 200)
    throw new Error(`History fetch failed (${resp.status})`);
  const episodes = ((_a = resp.json.episodes) != null ? _a : []).map((e) => {
    var _a2, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q;
    return {
      uuid: e.uuid,
      title: (_a2 = e.title) != null ? _a2 : "Untitled",
      podcastTitle: (_b = e.podcastTitle) != null ? _b : "Unknown Podcast",
      podcastUuid: (_c = e.podcastUuid) != null ? _c : "",
      podcastSlug: (_d = e.podcastSlug) != null ? _d : "",
      slug: (_e = e.slug) != null ? _e : "",
      author: (_f = e.author) != null ? _f : "",
      duration: (_g = e.duration) != null ? _g : 0,
      playedUpTo: (_h = e.playedUpTo) != null ? _h : 0,
      playingStatus: (_i = e.playingStatus) != null ? _i : 0,
      published: (_j = e.published) != null ? _j : "",
      url: (_k = e.url) != null ? _k : "",
      fileType: (_l = e.fileType) != null ? _l : "",
      fileSize: Number((_m = e.size) != null ? _m : 0),
      episodeSeason: (_n = e.episodeSeason) != null ? _n : 0,
      episodeNumber: (_o = e.episodeNumber) != null ? _o : 0,
      episodeType: (_p = e.episodeType) != null ? _p : "",
      starred: (_q = e.starred) != null ? _q : false
    };
  });
  return episodes;
}
async function apiFetchShowNotes(episodeUuid) {
  var _a;
  try {
    const resp = await (0, import_obsidian.requestUrl)({
      url: `https://cache.pocketcasts.com/episode/show_notes/${episodeUuid}`,
      method: "GET"
    });
    console.log(`PocketSync show_notes status=${resp.status}`, resp.json);
    if (resp.status !== 200)
      return "";
    return (_a = resp.json.show_notes) != null ? _a : "";
  } catch (e) {
    console.error("PocketSync show_notes fetch error", episodeUuid, e);
    return "";
  }
}
function podcastImageUrl(podcastUuid, size = 480) {
  return `https://static.pocketcasts.com/discover/images/webp/${size}/${podcastUuid}.webp`;
}
var PocketCastsView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_POCKETCASTS;
  }
  getDisplayText() {
    return "Pocket Casts History";
  }
  getIcon() {
    return "headphones";
  }
  async onOpen() {
    this.render([]);
    await this.refresh();
  }
  async refresh() {
    const { email, password } = this.plugin.settings;
    if (!email || !password) {
      this.renderError("Configure your Pocket Casts credentials in Settings.");
      return;
    }
    this.renderLoading();
    try {
      if (!this.plugin.settings.token) {
        this.plugin.settings.token = await apiLogin(email, password);
        await this.plugin.saveSettings();
      }
      let episodes;
      try {
        episodes = await apiFetchHistory(this.plugin.settings.token);
      } catch (e) {
        this.plugin.settings.token = await apiLogin(email, password);
        await this.plugin.saveSettings();
        episodes = await apiFetchHistory(this.plugin.settings.token);
      }
      const considered = episodes.filter(isConsidered);
      this.render(considered);
    } catch (err) {
      this.renderError(`Error: ${err.message}`);
    }
  }
  renderLoading() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("p", { text: "Loading listening history\u2026", cls: "pocketcasts-loading" });
  }
  renderError(msg) {
    const { contentEl } = this;
    contentEl.empty();
    const wrap = contentEl.createDiv({ cls: "pocketcasts-error" });
    wrap.createEl("span", { text: "\u26A0 " });
    wrap.createEl("span", { text: msg });
  }
  render(episodes) {
    const { contentEl } = this;
    contentEl.empty();
    const header = contentEl.createDiv({ cls: "pocketcasts-header" });
    header.createEl("h2", { text: "Pocket Casts" });
    const controls = header.createDiv({ cls: "pocketcasts-controls" });
    const refreshBtn = controls.createEl("button", { text: "Refresh" });
    refreshBtn.addEventListener("click", () => this.refresh());
    if (episodes.length === 0) {
      contentEl.createEl("p", { text: "No episodes found.", cls: "pocketcasts-empty" });
      return;
    }
    const stats = contentEl.createDiv({ cls: "pocketcasts-stats" });
    const totalListened = episodes.reduce((s, e) => s + (e.playedUpTo || 0), 0);
    const completed = episodes.filter((e) => e.playingStatus === 3).length;
    stats.createEl("span", { text: `${episodes.length} episodes` });
    stats.createEl("span", { text: " \xB7 " });
    stats.createEl("span", { text: `${completed} completed` });
    stats.createEl("span", { text: " \xB7 " });
    stats.createEl("span", { text: `${formatDuration(totalListened)} total` });
    const list = contentEl.createDiv({ cls: "pocketcasts-list" });
    for (const ep of episodes) {
      this.renderEpisode(list, ep);
    }
  }
  renderEpisode(container, ep) {
    const card = container.createDiv({ cls: "pocketcasts-card" });
    card.title = "Click to create a note for this episode";
    card.addEventListener("click", () => this.plugin.createEpisodeNote(ep));
    const topRow = card.createDiv({ cls: "pocketcasts-card-top" });
    const info = topRow.createDiv({ cls: "pocketcasts-card-info" });
    info.createEl("div", { text: ep.title, cls: "pocketcasts-episode-title" });
    info.createEl("div", { text: ep.podcastTitle, cls: "pocketcasts-podcast-title" });
    const meta = topRow.createDiv({ cls: "pocketcasts-card-meta" });
    const pct = progressPct(ep);
    const badge = pct >= 100 ? "100%" : `${pct}%`;
    meta.createEl("span", {
      text: badge,
      cls: pct >= 100 ? "pocketcasts-badge pocketcasts-badge-done" : "pocketcasts-badge"
    });
    meta.createEl("span", { text: "\u{1F4DD}", cls: "pocketcasts-note-icon", title: "Create note" });
    const bottomRow = card.createDiv({ cls: "pocketcasts-card-bottom" });
    if (ep.published) {
      bottomRow.createEl("span", { text: formatDate(ep.published), cls: "pocketcasts-date" });
    }
    bottomRow.createEl("span", {
      text: `${formatDuration(ep.playedUpTo)} / ${formatDuration(ep.duration)}`,
      cls: "pocketcasts-duration"
    });
    const barWrap = card.createDiv({ cls: "pocketcasts-progress-wrap" });
    const bar = barWrap.createDiv({ cls: "pocketcasts-progress-bar" });
    bar.style.width = `${pct}%`;
  }
};
var FileExistsModal = class extends import_obsidian.Modal {
  constructor(app, filename, resolve) {
    super(app);
    this.resolved = false;
    this.filename = filename;
    this.resolve = resolve;
  }
  pick(choice) {
    if (this.resolved)
      return;
    this.resolved = true;
    this.resolve(choice);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "Note already exists" });
    contentEl.createEl("p", { text: `"${this.filename}" already exists. What would you like to do?` });
    const btnRow = contentEl.createDiv({ cls: "pocketcasts-modal-buttons" });
    const openBtn = btnRow.createEl("button", { text: "Open existing" });
    openBtn.addEventListener("click", () => {
      this.pick("open");
      this.close();
    });
    const overwriteBtn = btnRow.createEl("button", { text: "Overwrite" });
    overwriteBtn.addClass("mod-warning");
    overwriteBtn.addEventListener("click", () => {
      this.pick("overwrite");
      this.close();
    });
    const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => {
      this.pick("cancel");
      this.close();
    });
  }
  onClose() {
    this.pick("cancel");
    this.contentEl.empty();
  }
};
var PocketCastsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Pocket Casts Sync" });
    new import_obsidian.Setting(containerEl).setName("Email").setDesc("Your Pocket Casts account email").addText(
      (text) => text.setPlaceholder("email@example.com").setValue(this.plugin.settings.email).onChange(async (value) => {
        this.plugin.settings.email = value.trim();
        this.plugin.settings.token = "";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Password").setDesc("Your Pocket Casts account password").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022").setValue(this.plugin.settings.password).onChange(async (value) => {
        this.plugin.settings.password = value;
        this.plugin.settings.token = "";
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Note Creation" });
    new import_obsidian.Setting(containerEl).setName("Note path").setDesc("Folder where podcast episode notes will be created.").addText(
      (text) => text.setPlaceholder("personal/podcasts").setValue(this.plugin.settings.notePath).onChange(async (value) => {
        this.plugin.settings.notePath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Note filename").setDesc("Filename template. Use {{podcast_name}} and {{podcast_episode}} as placeholders.").addText(
      (text) => text.setPlaceholder("{{podcast_name}} - {{podcast_episode}}.md").setValue(this.plugin.settings.noteFilename).onChange(async (value) => {
        this.plugin.settings.noteFilename = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Templater template file").setDesc(
      "Path to a Templater template file (without .md). All episode metadata is available via tp.frontmatter in the template. Leave empty to use the built-in default format."
    ).addText(
      (text) => text.setPlaceholder("_templater_templates/Podcast").setValue(this.plugin.settings.templaterFile).onChange(async (value) => {
        this.plugin.settings.templaterFile = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Open listening history").addButton(
      (btn) => btn.setButtonText("Open view").setCta().onClick(() => this.plugin.activateView())
    );
  }
};
var PocketCastsPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_POCKETCASTS, (leaf) => new PocketCastsView(leaf, this));
    this.addRibbonIcon("headphones", "Pocket Casts History", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-pocketcasts-history",
      name: "Open listening history",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "refresh-pocketcasts-history",
      name: "Refresh listening history",
      callback: async () => {
        const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_POCKETCASTS)[0];
        if (leaf) {
          leaf.view.refresh();
        } else {
          await this.activateView();
        }
      }
    });
    this.addSettingTab(new PocketCastsSettingTab(this.app, this));
    this.addStyles();
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_POCKETCASTS);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_POCKETCASTS);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (!leaf)
      return;
    await leaf.setViewState({ type: VIEW_TYPE_POCKETCASTS, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async createEpisodeNote(ep) {
    var _a, _b;
    const sanitize = (s) => s.replace(/[\\/:*?"<>|#^[\]]/g, "-").trim();
    const rawFilename = this.settings.noteFilename.replace("{{podcast_name}}", sanitize(ep.podcastTitle)).replace("{{podcast_episode}}", sanitize(ep.title));
    const filename = rawFilename.endsWith(".md") ? rawFilename : rawFilename + ".md";
    const folderPath = this.settings.notePath.replace(/\/+$/, "");
    const fullPath = folderPath ? `${folderPath}/${filename}` : filename;
    await this.ensureFolder(folderPath);
    const existing = this.app.vault.getAbstractFileByPath(fullPath);
    if (existing instanceof import_obsidian.TFile) {
      const choice = await new Promise(
        (resolve) => new FileExistsModal(this.app, filename, resolve).open()
      );
      if (choice === "cancel")
        return;
      if (choice === "open") {
        await this.app.workspace.openLinkText(fullPath, "", false);
        return;
      }
      await this.app.vault.delete(existing);
    }
    const showNotes = await apiFetchShowNotes(ep.uuid);
    const frontmatter = this.buildFrontmatter(ep, showNotes);
    const templaterPlugin = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b["templater-obsidian"];
    const templatePath = this.settings.templaterFile ? this.settings.templaterFile.endsWith(".md") ? this.settings.templaterFile : this.settings.templaterFile + ".md" : null;
    const templateFile = templatePath ? this.app.vault.getAbstractFileByPath(templatePath) : null;
    if (templaterPlugin && templateFile instanceof import_obsidian.TFile) {
      const noteFile = await this.app.vault.create(fullPath, frontmatter);
      await new Promise((resolve) => setTimeout(resolve, 500));
      try {
        await templaterPlugin.templater.write_template_to_file(templateFile, noteFile);
      } catch (e) {
        console.error("PocketSync: Templater error", e);
        new import_obsidian.Notice("Templater failed to apply template. Note created with frontmatter only.");
      }
      await this.app.workspace.openLinkText(fullPath, "", false);
    } else {
      const content = frontmatter + this.buildBasicContent(ep, showNotes);
      await this.app.vault.create(fullPath, content);
      await this.app.workspace.openLinkText(fullPath, "", false);
    }
    new import_obsidian.Notice(`Created podcast note: ${filename}`);
  }
  async ensureFolder(folderPath) {
    if (!folderPath)
      return;
    const parts = folderPath.split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(current)) {
        try {
          await this.app.vault.createFolder(current);
        } catch (e) {
        }
      }
    }
  }
  buildFrontmatter(ep, showNotes) {
    const esc = (s) => s.replace(/"/g, '\\"');
    const date = ep.published ? new Date(ep.published).toISOString().split("T")[0] : "";
    const imageUrl = podcastImageUrl(ep.podcastUuid);
    const lines = [
      "---",
      `podcast_title: "${esc(ep.podcastTitle)}"`,
      `episode_title: "${esc(ep.title)}"`,
      `author: "${esc(ep.author)}"`,
      `episode_uuid: "${ep.uuid}"`,
      `podcast_uuid: "${ep.podcastUuid}"`,
      `podcast_slug: "${ep.podcastSlug}"`,
      `episode_slug: "${ep.slug}"`,
      `published_date: ${date || '""'}`,
      `duration_seconds: ${ep.duration}`,
      `duration_formatted: "${formatDuration(ep.duration)}"`,
      `played_up_to_seconds: ${ep.playedUpTo}`,
      `played_up_to_formatted: "${formatDuration(ep.playedUpTo)}"`,
      `progress_percent: ${progressPct(ep)}`,
      `completed: ${ep.playingStatus === 3}`,
      `playing_status: ${ep.playingStatus}`,
      `starred: ${ep.starred}`,
      `audio_url: "${esc(ep.url)}"`,
      `image_url: "${imageUrl}"`
    ];
    if (ep.fileType)
      lines.push(`file_type: "${ep.fileType}"`);
    if (ep.fileSize)
      lines.push(`file_size_bytes: ${ep.fileSize}`);
    if (ep.episodeType)
      lines.push(`episode_type: "${ep.episodeType}"`);
    if (ep.episodeSeason)
      lines.push(`season: ${ep.episodeSeason}`);
    if (ep.episodeNumber)
      lines.push(`episode_number: ${ep.episodeNumber}`);
    lines.push(showNotes ? `description: |
  ${showNotes.trim().replace(/\n/g, "\n  ")}` : `description: ""`);
    lines.push(`tags:
  - podcast`, "---", "");
    return lines.join("\n");
  }
  buildBasicContent(ep, showNotes) {
    const date = ep.published ? formatDate(ep.published) : "";
    const status = ep.playingStatus === 3 ? "Completed" : "In Progress";
    const epLabel = [
      ep.episodeSeason ? `S${ep.episodeSeason}` : null,
      ep.episodeNumber ? `E${ep.episodeNumber}` : null
    ].filter(Boolean).join("");
    const imageUrl = podcastImageUrl(ep.podcastUuid);
    const lines = [
      `# ${ep.title}`,
      "",
      `![Podcast artwork](${imageUrl})`,
      "",
      `> [!info] Episode Details`,
      `> **Podcast**: ${ep.podcastTitle}`,
      ep.author ? `> **Author**: ${ep.author}` : null,
      date ? `> **Published**: ${date}` : null,
      epLabel ? `> **Episode**: ${epLabel}` : null,
      ep.episodeType ? `> **Type**: ${ep.episodeType}` : null,
      `> **Duration**: ${formatDuration(ep.duration)}`,
      `> **Progress**: ${formatDuration(ep.playedUpTo)} / ${formatDuration(ep.duration)} (${progressPct(ep)}%)`,
      `> **Status**: ${status}`,
      ep.starred ? `> **Starred**: yes` : null,
      ep.url ? `> **Audio**: [Listen](${ep.url})` : null,
      ""
    ];
    if (showNotes) {
      lines.push("## Description", "", showNotes.trim(), "");
    }
    lines.push("## Notes", "", "");
    return lines.filter((l) => l !== null).join("\n");
  }
  addStyles() {
    const style = document.createElement("style");
    style.id = "pocketcasts-styles";
    style.textContent = `
.pocketcasts-header {
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: 12px 16px 8px;
	border-bottom: 1px solid var(--background-modifier-border);
}
.pocketcasts-header h2 {
	margin: 0;
	font-size: 1.1em;
}
.pocketcasts-controls button {
	font-size: 0.8em;
	padding: 3px 10px;
}
.pocketcasts-stats {
	padding: 6px 16px;
	font-size: 0.8em;
	color: var(--text-muted);
	border-bottom: 1px solid var(--background-modifier-border);
}
.pocketcasts-loading,
.pocketcasts-empty {
	padding: 24px 16px;
	color: var(--text-muted);
	font-size: 0.9em;
}
.pocketcasts-error {
	padding: 16px;
	color: var(--text-error);
	font-size: 0.9em;
}
.pocketcasts-list {
	overflow-y: auto;
}
.pocketcasts-card {
	padding: 10px 16px 8px;
	border-bottom: 1px solid var(--background-modifier-border);
	cursor: pointer;
}
.pocketcasts-card:hover {
	background: var(--background-secondary-alt);
}
.pocketcasts-note-icon {
	margin-left: 6px;
	font-size: 0.85em;
	opacity: 0.4;
}
.pocketcasts-card:hover .pocketcasts-note-icon {
	opacity: 1;
}
.pocketcasts-card-top {
	display: flex;
	justify-content: space-between;
	align-items: flex-start;
	gap: 8px;
}
.pocketcasts-card-info {
	flex: 1;
	min-width: 0;
}
.pocketcasts-episode-title {
	font-size: 0.9em;
	font-weight: 600;
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
	color: var(--text-normal);
}
.pocketcasts-podcast-title {
	font-size: 0.78em;
	color: var(--text-muted);
	margin-top: 1px;
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}
.pocketcasts-card-meta {
	flex-shrink: 0;
}
.pocketcasts-badge {
	font-size: 0.75em;
	padding: 2px 6px;
	border-radius: 4px;
	background: var(--background-modifier-border);
	color: var(--text-muted);
}
.pocketcasts-badge-done {
	background: var(--interactive-accent);
	color: var(--text-on-accent);
}
.pocketcasts-card-bottom {
	display: flex;
	justify-content: space-between;
	margin-top: 4px;
	font-size: 0.74em;
	color: var(--text-faint);
}
.pocketcasts-progress-wrap {
	margin-top: 5px;
	height: 3px;
	background: var(--background-modifier-border);
	border-radius: 2px;
	overflow: hidden;
}
.pocketcasts-progress-bar {
	height: 100%;
	background: var(--interactive-accent);
	border-radius: 2px;
	transition: width 0.3s ease;
}
.pocketcasts-modal-buttons {
	display: flex;
	gap: 8px;
	justify-content: flex-end;
	margin-top: 16px;
}
`;
    document.head.appendChild(style);
  }
};
